### ISSUE TITLE
support for ghc 7.10

### ISSUE THREAD

**Issue by gregnwosu** [alanz/HaRe#23]
please

**Comment by alanz** [comment]
Its coming. See the https://github.com/alanz/HaRe/tree/wip branch

**Comment by tebello-thejane** [comment]
I'm glad to see you're working on it. Thanks. :-)

**Comment by alanz** [comment]
The current wip branch now works, provided you use ghc-exactprint from the wip branch on my repo there too.

Feel free to test it and report issues (I expect lots of them)

**Comment by alanz** [comment]
Version 0.8.0.0 is now on hackage.

Only supports 7.10.2, both for bulding and for the project being refactored
