### ISSUE TITLE
Set up .travis.yml for the elisp code

### ISSUE THREAD

**Issue by alanz** [alanz/HaRe#24]
At the moment the elisp has no tests.

As a precursor to adding proper tests, set up a .travis.yml to do the tests on commit, even if the tests are just placeholders initially.

**Comment by gracjan** [comment]
As a basis https://github.com/haskell/haskell-mode/blob/master/.travis.yml from haskell-mode can be used for hints.

**Comment by gracjan** [comment]
Fixed in #33.

**Comment by alanz** [comment]
Thanks
