### ISSUE TITLE
Integrate elisp code with haskell-mode

### ISSUE THREAD

**Issue by alanz** [alanz/HaRe#27]

**Comment by gracjan** [comment]
That is very far fetched. General tendency in haskell-mode is to keep it as a well working basis for other packages.

Also if I guess correctly a lot of ghc-mod would need to get in first and right now this is also quite far in the horizon.

**Comment by alanz** [comment]
I think the idea is more that is plays nice with haskell-mode, I guess.

**Comment by alanz** [comment]
Nothing to be done
